name: deploy github-resume-backend

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Environment Variables File for Production
        run: |
          echo "SEARCH_GITHUB_CLIENT_TOKEN=${{ secrets.SEARCH_GITHUB_CLIENT_TOKEN }}" >> ./src/config/env/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ./src/config/env/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ./src/config/env/.env
          echo "SLACK_WEB_HOOK=${{ secrets.SLACK_WEB_HOOK }}" >> ./src/config/env/.env
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> ./src/config/env/.env
        env:
          VARIABLE: ${{ secrets.VARIABLE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Image Build And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/aarch64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend
  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, Linux, ARM]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Docker run
        run: |
          docker stop github-resume-backend && docker rm github-resume-backend && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend:latest

          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend:latest --platform linux/arm64

          docker run -d -p 3000:3000 --name github-resume-backend --add-host=host.docker.internal:host-gateway ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend:latest