name: deploy github-resume-backend

on:
  push:
    branches: [feature/backend-1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Environment Variables File for Production
        run: |
          echo "VARIABLE=$VARIABLE" >> ./src/config/env/.env
        env:
          VARIABLE: ${{ secrets.VARIABLE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Image Build And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend
  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, github-resume]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Docker run
        run: |
          docker stop github-resume-backend && docker rm github-resume-backend && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend:latest

          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend:latest

          docker run -d -p 80:3000 --name github-resume-backend --add-host=host.docker.internal:host-gateway ${{ secrets.DOCKERHUB_USERNAME }}/github-resume-backend:latest